# Generated by Django 5.1.4 on 2025-02-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_questions_studymaterialfile_studymaterialnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterialfile',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studymaterialnotes',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
