# Generated by Django 5.1.4 on 2025-02-11 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_studymaterialfile_name_studymaterialnotes_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='studymaterialfile',
            name='file',
            field=models.FileField(upload_to='media/files'),
        ),
        migrations.AddField(
            model_name='questions',
            name='lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.language'),
        ),
    ]
